package com.hello.micro.service.mapper.food;

import com.hello.micro.service.model.food.Flavor;
import com.hello.micro.service.model.food.FlavorExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FlavorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavor
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    long countByExample(FlavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavor
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int deleteByExample(FlavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavor
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavor
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int insert(Flavor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavor
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int insertSelective(Flavor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavor
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    List<Flavor> selectByExample(FlavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavor
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    Flavor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavor
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") Flavor record, @Param("example") FlavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavor
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByExample(@Param("record") Flavor record, @Param("example") FlavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavor
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByPrimaryKeySelective(Flavor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flavor
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByPrimaryKey(Flavor record);
}