package com.hello.micro.service.mapper.food;

import com.hello.micro.service.model.food.Style;
import com.hello.micro.service.model.food.StyleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table style
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    long countByExample(StyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table style
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int deleteByExample(StyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table style
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table style
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int insert(Style record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table style
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int insertSelective(Style record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table style
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    List<Style> selectByExample(StyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table style
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    Style selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table style
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") Style record, @Param("example") StyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table style
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByExample(@Param("record") Style record, @Param("example") StyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table style
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByPrimaryKeySelective(Style record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table style
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByPrimaryKey(Style record);
}