package com.hello.micro.service.mapper.food;

import com.hello.micro.service.model.food.UserMaterial;
import com.hello.micro.service.model.food.UserMaterialExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_material
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    long countByExample(UserMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_material
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int deleteByExample(UserMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_material
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_material
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int insert(UserMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_material
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int insertSelective(UserMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_material
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    List<UserMaterial> selectByExample(UserMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_material
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    UserMaterial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_material
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserMaterial record, @Param("example") UserMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_material
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByExample(@Param("record") UserMaterial record, @Param("example") UserMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_material
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByPrimaryKeySelective(UserMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_material
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByPrimaryKey(UserMaterial record);
}