package com.hello.micro.service.mapper.food;

import com.hello.micro.service.model.food.UserFood;
import com.hello.micro.service.model.food.UserFoodExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserFoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    long countByExample(UserFoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int deleteByExample(UserFoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int insert(UserFood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int insertSelective(UserFood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    List<UserFood> selectByExample(UserFoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    UserFood selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserFood record, @Param("example") UserFoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByExample(@Param("record") UserFood record, @Param("example") UserFoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByPrimaryKeySelective(UserFood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    int updateByPrimaryKey(UserFood record);
}