spring:
  application:
    name: read-server
  profiles:
    active: online

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.xupt.read.server.model
