package com.hello.micro.service.model.food;

import java.io.Serializable;

public class Flavor implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavor.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flavor.name
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table flavor
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavor.id
     *
     * @return the value of flavor.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavor.id
     *
     * @param id the value for flavor.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flavor.name
     *
     * @return the value of flavor.name
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flavor.name
     *
     * @param name the value for flavor.name
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}