package com.hello.micro.service.model.food;

import java.io.Serializable;

public class Food implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.name
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.flavor_ids
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private String flavorIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.material_ids
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private String materialIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.pictures
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private String pictures;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.style_id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private Integer styleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.id
     *
     * @return the value of food.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.id
     *
     * @param id the value for food.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.name
     *
     * @return the value of food.name
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.name
     *
     * @param name the value for food.name
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.flavor_ids
     *
     * @return the value of food.flavor_ids
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public String getFlavorIds() {
        return flavorIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.flavor_ids
     *
     * @param flavorIds the value for food.flavor_ids
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setFlavorIds(String flavorIds) {
        this.flavorIds = flavorIds == null ? null : flavorIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.material_ids
     *
     * @return the value of food.material_ids
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public String getMaterialIds() {
        return materialIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.material_ids
     *
     * @param materialIds the value for food.material_ids
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setMaterialIds(String materialIds) {
        this.materialIds = materialIds == null ? null : materialIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.pictures
     *
     * @return the value of food.pictures
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public String getPictures() {
        return pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.pictures
     *
     * @param pictures the value for food.pictures
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setPictures(String pictures) {
        this.pictures = pictures == null ? null : pictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.style_id
     *
     * @return the value of food.style_id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public Integer getStyleId() {
        return styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.style_id
     *
     * @param styleId the value for food.style_id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setStyleId(Integer styleId) {
        this.styleId = styleId;
    }
}