package com.hello.micro.service.model.food;

import java.io.Serializable;

public class Material implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.name
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private Integer name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.id
     *
     * @return the value of material.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.id
     *
     * @param id the value for material.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.name
     *
     * @return the value of material.name
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public Integer getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.name
     *
     * @param name the value for material.name
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setName(Integer name) {
        this.name = name;
    }
}