package com.hello.micro.service.model.food;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cookie_id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private Integer cookieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cookie_id
     *
     * @return the value of user.cookie_id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public Integer getCookieId() {
        return cookieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cookie_id
     *
     * @param cookieId the value for user.cookie_id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setCookieId(Integer cookieId) {
        this.cookieId = cookieId;
    }
}