package com.hello.micro.service.model.food;

import java.io.Serializable;

public class UserFood implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_food.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_food.user_id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_food.food_id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private Integer foodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_food.coefficient
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private Integer coefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_food
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_food.id
     *
     * @return the value of user_food.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_food.id
     *
     * @param id the value for user_food.id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_food.user_id
     *
     * @return the value of user_food.user_id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_food.user_id
     *
     * @param userId the value for user_food.user_id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_food.food_id
     *
     * @return the value of user_food.food_id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public Integer getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_food.food_id
     *
     * @param foodId the value for user_food.food_id
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_food.coefficient
     *
     * @return the value of user_food.coefficient
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public Integer getCoefficient() {
        return coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_food.coefficient
     *
     * @param coefficient the value for user_food.coefficient
     *
     * @mbg.generated Mon Apr 06 09:51:22 CST 2020
     */
    public void setCoefficient(Integer coefficient) {
        this.coefficient = coefficient;
    }
}